
package com.mycompany.views;

import com.mycompany.dsfr.DAODisfracesImpl;
import com.mycompany.dsfr.Dashboard;
import com.mycompany.utils.Utils;
import java.awt.Color;
import com.mycompany.interfaces.DAODisfraces;

/**
 *
 * @author cristian
 */
public class UpDisfraces extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Disfraces dsfrEdition;

    boolean fromEventDetails = false;
    com.mycompany.models.Evento eventoOrigen;

    public UpDisfraces() {
        initComponents();
        InitStyles();
    }

    public UpDisfraces(com.mycompany.models.Disfraces dsfr, com.mycompany.models.Evento evento) {
        initComponents();
        isEdition = true;
        dsfrEdition = dsfr;

        fromEventDetails = true;
        if (evento != null) {
            fromEventDetails = true;
            eventoOrigen = evento;
        }

        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
        titleTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del disfraz");
        tematicaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la temática del disfraz");
        descjTextArea1.putClientProperty("JTextArea.placeholderText", "Ingrese la descripción del disfraz");
        stockTxt.putClientProperty("JTextField.placeholderText", "Ingrese el stock total");
        tallaTxt.putClientProperty("JTextField.placeholderText", "Talla");
        dispTxt.putClientProperty("JTextField.placeholderText", "Disfraces disponibles");

        estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Nuevo", "Usado", "En reparación"}
        ));

        if (isEdition && dsfrEdition != null) {
            title.setText("Editar disfraz");
            button.setText("Guardar");

            titleTxt.setText(dsfrEdition.getTitle());
            tematicaTxt.setText(dsfrEdition.getTematica());
            descjTextArea1.setText(dsfrEdition.getDescription());
            tallaTxt.setText(dsfrEdition.getTalla());
            estadojComboBox.setSelectedItem(dsfrEdition.getEstado());
            stockTxt.setText(String.valueOf(dsfrEdition.getStock()));
            dispTxt.setText(String.valueOf(dsfrEdition.getAvailable()));

            if (isEdition && dsfrEdition != null) {
                estadojComboBox.setSelectedItem(dsfrEdition.getEstado());
                dispTxt.setText(String.valueOf(dsfrEdition.getAvailable()));

                if ("En reparación".equalsIgnoreCase(dsfrEdition.getEstado())) {
                    dispTxt.setEnabled(false);
                    dispTxt.setText("0");
                } else {
                    dispTxt.setEnabled(true);
                }
            } else {
                dispTxt.setEnabled(true);
            }
        }

        estadojComboBox.addActionListener(e -> {
            String estado = (String) estadojComboBox.getSelectedItem();

            if ("En reparación".equalsIgnoreCase(estado)) {
                dispTxt.setText("0");
                dispTxt.setEnabled(false);
            } else {
                dispTxt.setEnabled(true);
                if (isEdition && dsfrEdition != null) {
                    dispTxt.setText(String.valueOf(dsfrEdition.getAvailable()));
                }
            }
        });
    }

    private boolean validarDisponiblesAlGuardar() {
        try {
            if (!dispTxt.isEnabled()) {
                return true;
            }

            int stock = Integer.parseInt(stockTxt.getText().trim());
            int disp = Integer.parseInt(dispTxt.getText().trim());

            if (disp > stock) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El valor de Disponibles no puede ser mayor al Stock.\n",
                        "AVISO", javax.swing.JOptionPane.WARNING_MESSAGE);
                dispTxt.setText(String.valueOf(stock));
                return false;
            }
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        tematicaLbl = new javax.swing.JLabel();
        tematicaTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        descLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        stockTxt = new javax.swing.JTextField();
        dispTxt = new javax.swing.JTextField();
        dispLbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        tallaLbl = new javax.swing.JLabel();
        tallaTxt = new javax.swing.JTextField();
        estadoLbl = new javax.swing.JLabel();
        estadojComboBox = new javax.swing.JComboBox<>();
        cancelbutton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descjTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(752, 427));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(752, 427));

        title.setText("Subir nuevo Disfraz");

        titleLbl.setText("Nombre *");

        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });

        tematicaLbl.setText("Temática *");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        descLbl.setText("Descripción *");

        stockLbl.setText("Stock *");
        stockLbl.setToolTipText("");

        stockTxt.setToolTipText("");

        dispTxt.setToolTipText("");

        dispLbl.setText("Disponibles *");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Subir");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        tallaLbl.setText("Talla *");
        tallaLbl.setToolTipText("");

        tallaTxt.setToolTipText("");

        estadoLbl.setText("Estado");
        estadoLbl.setToolTipText("");

        estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelbutton1.setBackground(new java.awt.Color(18, 90, 173));
        cancelbutton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelbutton1.setForeground(new java.awt.Color(255, 255, 255));
        cancelbutton1.setText("Cancelar");
        cancelbutton1.setBorderPainted(false);
        cancelbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbutton1ActionPerformed(evt);
            }
        });

        descjTextArea1.setColumns(20);
        descjTextArea1.setRows(5);
        descjTextArea1.setLineWrap(true);
        descjTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descjTextArea1);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleTxt)
                    .addComponent(tematicaTxt)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(descLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(245, 245, 245))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(263, 263, 263))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(tematicaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(259, 259, 259))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(cancelbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(182, 182, 182))
                    .addComponent(jScrollPane1))
                .addGap(46, 46, 46)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stockTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(tallaTxt)
                            .addComponent(tallaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadojComboBox, 0, 108, Short.MAX_VALUE)
                            .addComponent(dispTxt)
                            .addComponent(estadoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dispLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)
                        .addGap(22, 22, 22)
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tematicaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(tematicaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(descLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(tallaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)
                                        .addComponent(tallaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(stockLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)
                                        .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(estadoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)
                                        .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(dispLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)
                                        .addComponent(dispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)))))
                .addGap(18, 18, 18)
                .addComponent(cancelbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String mtitle = titleTxt.getText().trim();
        String tematica = tematicaTxt.getText().trim();
        String desc = descjTextArea1.getText().trim();
        String talla = tallaTxt.getText().trim();
        String estado = (String) estadojComboBox.getSelectedItem();
        String stock = stockTxt.getText().trim();
        String disp = dispTxt.getText().trim();

        if (mtitle.isEmpty() || tematica.isEmpty() || desc.isEmpty() || talla.isEmpty()
                || estado == null || estado.isEmpty() || stock.isEmpty() || disp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe llenar todos los campos obligatorios. (*) \n",
                    "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(stock) || !Utils.isNumeric(disp)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los campos Stock y Disponibles deben ser números enteros. \n",
                    "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            stockTxt.requestFocus();
            return;
        }

        if (!validarDisponiblesAlGuardar()) {
            return;
        }
        com.mycompany.models.Disfraces dsfr = isEdition ? dsfrEdition : new com.mycompany.models.Disfraces();
        dsfr.setTitle(mtitle);
        dsfr.setTematica(tematica);
        dsfr.setDescription(desc);
        dsfr.setTalla(talla);
        dsfr.setEstado(estado);
        dsfr.setStock(Integer.parseInt(stock));
        dsfr.setAvailable(Integer.parseInt(disp));

        try {
            DAODisfraces dao = new DAODisfracesImpl();

            if (!isEdition) {
                dao.registrar(dsfr);
            } else {
                dao.modificar(dsfr);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Disfraz " + successMsg + " exitosamente.\n",
                    "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                titleTxt.setText("");
                tematicaTxt.setText("");
                descjTextArea1.setText("");
                tallaTxt.setText("");
                stockTxt.setText("");
                dispTxt.setText("");
                estadojComboBox.setSelectedIndex(0);
            }
            if (fromEventDetails && eventoOrigen != null) {
                Dashboard.ShowJPanel(new EventDetails(eventoOrigen));
            } else {
                Dashboard.ShowJPanel(new Costumes());
            }

        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al " + errorMsg + " el disfraz. \n",
                    "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void cancelbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbutton1ActionPerformed
        if (fromEventDetails && eventoOrigen != null) {
            Dashboard.ShowJPanel(new EventDetails(eventoOrigen));
        } else {
            Dashboard.ShowJPanel(new Costumes());
        }

    }//GEN-LAST:event_cancelbutton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JButton cancelbutton1;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextArea descjTextArea1;
    private javax.swing.JLabel dispLbl;
    private javax.swing.JTextField dispTxt;
    private javax.swing.JLabel estadoLbl;
    private javax.swing.JComboBox<String> estadojComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JLabel tallaLbl;
    private javax.swing.JTextField tallaTxt;
    private javax.swing.JLabel tematicaLbl;
    private javax.swing.JTextField tematicaTxt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
